language: scala
matrix:
  include:
  - jdk: oraclejdk8
    scala: 2.11.8
    env:
    - HAZELCAST=3.7.4 AKKA=2.4.0
  - jdk: oraclejdk8
    scala: 2.11.8
    env:
    - HAZELCAST=3.7.4 AKKA=2.4.16
  - jdk: oraclejdk8
    scala: 2.11.8
    env:
    - HAZELCAST=3.8.3 AKKA=2.5.3
  - jdk: oraclejdk8
    scala: 2.12.1
    env:
    - HAZELCAST=3.7.4 AKKA=2.4.12
  - jdk: oraclejdk8
    scala: 2.12.1
    env:
    - HAZELCAST=3.6.7 AKKA=2.4.16
  - jdk: oraclejdk8
    scala: 2.12.1
    env:
    - HAZELCAST=3.7.4 AKKA=2.4.16
  - jdk: oraclejdk8
    scala: 2.12.1
    env:
    - HAZELCAST=3.8.3 AKKA=2.5.3
install: true
script:
   - ./gradlew -Dscala.version=${TRAVIS_SCALA_VERSION} -Dhazelcast.version=${HAZELCAST} clean assemble testScoverage reportScoverage checkScoverage
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
