language: scala
scala:
   - 2.11.8
   - 2.12.1
jdk:
   - oraclejdk8
install: true
script:
   - ./gradlew -Dscala.version=${TRAVIS_SCALA_VERSION} assemble check
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
